name: Build Bookdown

on:
  push:
  schedule:
    # Every Monday at 06:00 UTC
    - cron: "0 6 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            bookdown
            rmarkdown
            ggplot2
            dplyr
            magrittr
            tidyr
            readxl
            flextable
            ggfortify
            DHARMa
            scales

      - name: Build book (gitbook)
        run: Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook')"
